server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:    # Eureka 서버에 등록될 Eureka Client 역할
      defaultZone: http://127.0.0.1:8761/eureka
